basex-core/src/main/java/org/basex/core/Text.java
basex-core/src/main/java/org/basex/gui/GUIOptions.java
basex-core/src/main/java/org/basex/gui/GUIPopupCmd.java
basex-core/src/main/java/org/basex/gui/layout/BaseXKeys.java
basex-core/src/main/java/org/basex/gui/layout/BaseXPopup.java
basex-core/src/main/java/org/basex/gui/view/project/ProjectDir.java
basex-core/src/main/java/org/basex/gui/view/project/ProjectTree.java
basex-core/src/main/java/org/basex/gui/view/project/ProjectView.java
basex-core/src/main/resources/lang/Dutch.lang
basex-core/src/main/resources/lang/English.lang
basex-core/src/main/resources/lang/French.lang
basex-core/src/main/resources/lang/German.lang
basex-core/src/main/resources/lang/Hungarian.lang
basex-core/src/main/resources/lang/Indonesian.lang
basex-core/src/main/resources/lang/Italian.lang
basex-core/src/main/resources/lang/Japanese.lang
basex-core/src/main/resources/lang/Mongolian.lang
basex-core/src/main/resources/lang/Romanian.lang
basex-core/src/main/resources/lang/Russian.lang
basex-core/src/main/resources/lang/Spanish.lang

Add a GUI popup menu option to hide hidden files in the project view.

[ADD] show/hide hidden files in project view

---

basex-core/src/main/java/org/basex/query/expr/IterMap.java
basex-core/src/test/java/org/basex/query/ast/InlineTest.java

Inlining into simple mapping operator.

---

basex-core/src/main/java/org/basex/query/QueryParser.java
basex-core/src/main/java/org/basex/query/func/Closure.java
basex-core/src/main/java/org/basex/query/func/FuncLit.java
basex-core/src/main/java/org/basex/query/func/StaticFuncs.java
basex-core/src/main/java/org/basex/query/value/item/FuncItem.java
basex-core/src/main/java/org/basex/query/value/type/FuncType.java
basex-core/src/test/java/org/basex/query/ast/InlineTest.java
basex-tests/src/main/java/org/basex/tests/w3c/QT3TS.java

Fix for GH-1052

---

basex-api/.settings/checkstyle.xml
basex-core/.settings/checkstyle.xml
basex-examples/.settings/checkstyle.xml
basex-tests/.settings/checkstyle.xml

[FIX] Checkstyle: Deactivate checks removed in the latest version.

---

basex-api/src/main/php/BaseXClient.php

[MOD] PHP Client, added digest authentication

---

README.md

Show a nice little status widget of the current build status

[MIN] Teamcity integration

---

basex-api/src/main/java/org/basex/http/webdav/BXServletRequest.java

Remove superfluous System.out.println.

[FIX] WebDAV: character encoding issues. #1184

---

basex-core/src/main/java/org/basex/query/value/item/Uri.java
basex-core/src/test/java/org/basex/query/value/item/UriTest.java

Fixes the original problem from GH-928 (i.e. correct URI resolving is not included).

[FIX] GH-928: RFC 3986 URI parser

---

basex-api/src/main/python/BaseXClient.py

Tidy up the code (very minor) to make it PEP8 standard.

PEP8 tidy up

---

basex-core/src/main/java/org/basex/query/value/map/TrieList.java

Avoid copying unchanged keys in TrieList

---

basex-core/src/main/java/org/basex/query/func/Function.java
basex-core/src/main/java/org/basex/query/func/fn/FnRandomNumberGenerator.java
basex-core/src/main/java/org/basex/query/var/Var.java

Fixes fn:random-number-generator(...).

---

README.md

Hey Jens, I think this should be BaseXRepo instead of BaseXModule, right?

Docker: s/BaseXModule/BaseXRepo

---

pom.xml

As discussed the little update to the pom.xml required to comply the OSSRH standards.
You will have to sign the packages with pgp, for setting it up see http://central.sonatype.org/pages/working-with-pgp-signatures.html for instructions. Then you will have to modify your settings.xml from Maven (.m2/settings.xml) like this:
```
<settings>
<profiles>
<profile>
<id>ossrh</id>
<activation>
<activeByDefault>true</activeByDefault>
</activation>
<properties>
<gpg.executable>gpg2</gpg.executable>
<gpg.passphrase>the_pass_phrase</gpg.passphrase>
</properties>
</profile>
</profiles>
</settings>
```
The actually signing will be done by the `maven-gpg-plugin`. 
When this is set up it should automatically release the artifacts to OSSRH when you run `mvn deploy`.
However, there is still one issue …

Maven Central

---

basex-core/src/main/java/org/basex/query/func/sql/SqlExecutePrepared.java

Removed parameter count check at all.
This avoids an additional roundtrip to database by getParameterMetaData and oracle too many open cursor issue.
mysql, oracle and postgresql will throw SQLException on too few or too many parameters.
sqlite will only throw SQLException on too few parameters. On too many it will throw  java.lang.ArrayIndexOutOfBoundsException.
So beside SQLException also any other exception is catched also and reported as BaseX SQL Exception assuming its SQL-related problem.

[MOD] removed parameter count-check on sql:execute-prepared

---

basex-api/src/main/c/basexdbc.c
basex-api/src/main/c/basexdbc.h
basex-api/src/main/c/md5.h
basex-api/src/main/c/readstring.h

Support for newer authentication model, with comments.

Support for newer authentication method

---

Dockerfile

[FIX] Updated Dockerfile to reflect 9.0 Changes

---

README.md

I have added a separate section for BaseX 9.0. I've tried to align it with the information on the wiki (I think the wiki could be updated a little further too).
http://docs.basex.org/wiki/Docker

Updates README for 9.0

---

basex-core/src/main/java/org/basex/util/http/HttpClient.java

Related: #1612
See https://stackoverflow.com/questions/25163131/httpurlconnection-invalid-http-method-patch/40606633#40606633
---
But feel free to close it.
Because might not really be future proof… 
```bash
[WARNING] /Users/michael/Code/basex/basex-core/src/main/java/org/basex/util/http/HttpClient.java:
[31,34] sun.net.www.protocol.https.HttpsURLConnectionImpl is internal proprietary API and may be removed in a future release
```

Set HTTP method in delegate for HttpsURLConnection

---

basex-api/.project
basex-api/src/main/java/org/basex/http/ws/WebSocket.java
basex-api/src/main/java/org/basex/http/ws/WsPool.java
basex-api/src/main/java/org/basex/modules/Ws.java
basex-api/src/main/webapp/chat/chat-ws.xqm
basex-api/src/main/webapp/chat/chat.xqm
basex-api/src/main/webapp/restxq.xqm
basex-api/src/main/webapp/static/chat.js
basex-api/src/main/webapp/static/style.css
basex-core/.project
basex-examples/.project
basex-tests/.project

* XQuery-Function for closing websockets added
* Private messages in chat possible

ADD ws:close-Function, ADD private msg in chat

---

basex-api/src/main/java/org/basex/modules/Sessions.java

https://github.com/BaseXdb/basex/issues/1620

Fix sessions:set

---

basex-api/src/main/java/org/basex/http/ws/WebSocket.java

https://github.com/BaseXdb/basex/issues/1626

1626: WebSockets: Error Handling

---

basex-core/src/main/java/org/basex/BaseXGUI.java
basex-core/src/main/java/org/basex/gui/GUI.java
basex-core/src/main/java/org/basex/gui/GUIMacOS.java
basex-core/src/main/java/org/basex/gui/GUIMacOSX.java
basex-core/src/main/java/org/basex/gui/GUIMacOSX9.java

macOS GUI: Fix keyboard shortcuts on JDK9+

---

basex-core/src/main/java/org/basex/query/value/map/TrieList.java
basex-core/src/test/java/org/basex/query/func/MapModuleTest.java

Proper merge logic when merging two collision lists.

Fix for GH-1779

---

basex-api/src/main/python/BaseXClient/BaseXClient.py
basex-api/src/main/python/UTF16Example.py

gh1555-python

---

basex-core/src/main/java/org/basex/gui/GUI.java
basex-core/src/main/java/org/basex/gui/GUIMenuCmd.java
basex-core/src/main/java/org/basex/gui/layout/BaseXLayout.java

[FIX] macOS Perform Quit

---

basex-core/src/main/java/org/basex/query/QueryError.java

This is no longer appropriate.

Remove GML version from error message

---

basex-core/src/main/java/org/basex/query/util/format/Formatter.java

This is a correction of last week's changes, which also fixes QT4 test case `format-time-023u`.

Correction of fractional seconds formatting

---

basex-core/src/main/java/org/basex/query/func/fn/RegEx.java
basex-core/src/main/java/org/basex/query/util/regex/parse/RegExLexer.java
basex-core/src/main/java/org/basex/query/util/regex/parse/RegExParser.java
basex-core/src/main/javacc/regex.jj

This change set adds support in regular expressions per qt4cg/qtspecs#1022.

Allow comments in regular expressions

---

basex-core/src/main/java/org/basex/query/QueryParser.java
basex-core/src/test/java/org/basex/query/expr/RecordTest.java

This change adds support for empty record types as per qt4cg/qtspecs#1577.

Empty record types

---

basex-core/src/main/java/org/basex/query/util/format/DecFormatter.java

These changes adapt to qt4cg/qtspecs#1250, by implementing the new notation for separating marker and rendition of several decimal format properties, and allowing an arbitrary string as the value of `minus-sign`, rather than a single character.

Adapt `DecFormatter` to recent specification changes

---

basex-core/src/main/java/org/basex/query/func/Function.java

`fn:html-doc` signature and declaration

---

basex-core/src/main/java/org/basex/query/QueryParser.java
basex-core/src/main/java/org/basex/query/expr/ALookup.java
basex-core/src/main/java/org/basex/query/expr/DeepLookup.java
basex-core/src/main/java/org/basex/query/expr/Lookup.java
basex-core/src/test/java/org/basex/query/expr/LookupTest.java

This change adds support for lookup modifiers.

Add support for lookup modifiers

---

basex-core/src/main/java/org/basex/query/QueryParser.java

These changes adapt the XQuery parser to the recent syntax changes with respect to computed constructors, QName literals, and pragmas.
The corresponding QT4 tests have been adapted in qt4cg/qt4tests#237.

Adapt XQuery parser to new syntax for computed constructors, QName literals, and pragmas

---

basex-core/src/main/java/org/basex/query/QueryError.java
basex-core/src/main/java/org/basex/query/QueryParser.java
basex-core/src/main/java/org/basex/query/ann/Annotation.java
basex-core/src/main/java/org/basex/query/expr/Lookup.java
basex-core/src/main/java/org/basex/query/func/map/MapGet.java
basex-core/src/main/java/org/basex/query/func/util/UtilMapValueAt.java
basex-core/src/main/java/org/basex/query/util/list/AnnList.java
basex-core/src/main/java/org/basex/query/value/item/FuncItem.java
basex-core/src/test/java/org/basex/query/expr/XQuery4Test.java

This change replaces the `%method` annotation by the new method call operator `?>`.

Remove `%method` annotation, add method call operator `?>`
