BaseXdb/basex

basex-api/src/main/webapp/dba/util.xqm

When an absolute address was used, the redirection possibly stripped the base path away. Especially using BaseX as a Tomcat webapp, the redirection was broken. Instead of the correct redirection:
``http://localhost:8080/webapp-name/dba`` -> ``http://localhost:8080/webapp-name/dba/databases``
this incorrect was produced:
``http://localhost:8080/webapp-name/dba`` -> ``http://localhost:8080/dba/databases``
Using a relative address should work *always*.
This solves a problem partially mentioned in #1060

Changed redirect to a relative address

---

basex-core/src/main/java/org/basex/query/func/Function.java
basex-core/src/main/java/org/basex/query/func/hof/HofScanLeft.java
basex-core/src/main/java/org/basex/query/func/hof/HofTakeWhile.java

* `hof:take-while($seq, $pred)` is equivalent to:
```xquery
declare function hof:take-while($seq, $pred) {
if(empty($seq) or not($pred(head($seq)))) then ()
else (
head($seq),
hof:take-while(tail($seq), $pred)
)
};
```
* `hof:scan-left($seq, $start, $f)` is equivalent to:
```xquery
declare function hof:scan-left($seq, $acc, $f) {
if(empty($seq)) then $acc
else (
$acc,
hof:scan-left(tail($seq), $f($acc, head($seq)), $f)
)
};
```

Two more HOFs: `hof:take-while($seq, $pred)` and `hof:scan-left($seq, $start, $f)`.

---

basex-core/src/main/java/org/basex/util/Util.java

When starting in service mode, system properties got lost as the key of the property was not copied into the arguments of the new process.

Retain system properties when starting in service mode

---

basex-api/etc/basexhttp
basex-core/etc/basex
basex-core/etc/basexgui
basex-core/etc/basexserver

BaseX sets `-cp` when starting java to include its own classes, but thus overwrites the `$CLASSPATH` environment variable (java ignores it when `-cp` is set). This does not leave the developer the choice to use environment variables for loading additional helper classes, which sometimes is easier and cleaner compared to linking into the BaseX `lib` folder (or even isn't possible if running on a shared host without write privileges to `/usr`).
With the patch, for example Apache batik could be loaded using
export CLASSPATH=/usr/share/java/batik.jar
basexhttp

Do not ignore $CLASSPATH additions

---

basex-api/src/main/webapp/dba/files/js.js

Explicitly setting Content-Type to text/plain in the request function of js.js. When it is not set, Safari (testing on 7.1.6 Mac) defaults to 'application/xml' and so BaseX refuses to accept anything that isn't XML. This can be seen when trying to save an xquery.
(Firefox defaults to 'text/plain' so there shouldn't be any change in behaviour there.)
I think I've checked for all current cases where this function is called as POST with data (the only time it'll be a problem) and text/plain works for all.

Explicitly set Content-Type when making XHR request from DBA

---

basex-api/src/main/webapp/dba/files/editor.js
basex-api/src/main/webapp/dba/modules/tmpl.xqm
basex-api/src/main/webapp/dba/queries/queries.xqm

It's not to the level of sophistication of the GUI but I've used CodeMirror to implement basic syntax highlighting in the Editor portion of the Queries screen in DBA.
This pull request has the required changes to the BaseX files.
Additionally you need to have the CodeMirror files. As I'm not sure how you include (or would include) files from other projects in BaseX so I haven't added them here.
I put a folder in 'files' called 'codemirror'. Inside there:
./lib/codemirror.css
./lib/codemirror.js
./mode/xquery/xquery.js
./LICENSE

Syntax highlighting in Queries editor

---

basex-api/src/main/webapp/dba/databases/optimize.xqm

Pressing Optimize on the databases screens fails with an error that $names is not defined.
In optimize.xqm the function string call to util:update contains the variable name $names when the map variable is called $n. This now matches the function in databases.xqm.

Correct variable name in drop() function in Optimize

---

basex-api/src/main/webapp/dba/files/editor.js
basex-api/src/main/webapp/dba/files/js.js
basex-api/src/main/webapp/dba/modules/tmpl.xqm
basex-api/src/main/webapp/dba/queries/queries.xqm

This pull request has the required changes to the BaseX files.
Additionally you need to have the CodeMirror files. As I'm not sure how you include (or would include) files from other projects in BaseX so I haven't added them here.
I put a folder in 'files' called 'codemirror'. Inside there:
./lib/codemirror.css
./lib/codemirror.js
./mode/xquery/xquery.js
./mode/xml/xml.js
./LICENSE
In this revised version:
- syntax highlighting of both the editor and result (XQuery and XML respectively)
- the realtime mode should work again
- resizing of the areas by dragging proved too difficult but I've implemented a function to expand them to the available screen height
- I've added a keybinding on the editor (CTRL-ENTER and CMD-ENTER) that will run the query. It's not the SHIFT-TAB you had before but …

Syntax highlighting in Queries (2)

---

basex-api/src/main/webapp/dba/settings/settings.xqm
basex-core/src/main/java/org/basex/core/locks/DBLocking.java
basex-core/src/test/java/org/basex/core/LockingTest.java

BaseX ran into a deadlock when a global read lock with a
concurrent local write lock was requested.

[FIX] Allow global read lock with concurrent write lock

---

basex-api/src/main/webapp/dba/databases/resources/query.xqm
basex-api/src/main/webapp/dba/queries/queries.xqm
basex-api/src/main/webapp/dba/static/js.js

Otherwise, the entity body can easily be too large.
HTTP Code 413 "Entity Too Large" is returned in these cases, the limit is even quite low normally.

[MOD] Query should be sent as POST parameter 

---

basex-api/src/main/c#/BaseXClient.cs

Now the session constructor uses the nonce sent by BaseX server when opening a session.

C# Client support for BaseX 8.x.

---

basex-core/src/main/java/org/basex/build/DirParser.java

Hi Christian,
Thanks for adding this feature! It seems to work well. I noticed that the archive file name is being converted to lower case in the path. This pull request is to use the original casing of the archive file name. 
Vincent

Use original casing of archive name.

---

basex-core/src/test/java/org/basex/query/value/item/UriTest.java

JUnit before 4.12 requires an iterable to be passed for parametrized tests.
Converted Object[][] to Collection<Object[]> to resolve the issue for older
JUnit setups.
https://github.com/junit-team/junit/blob/master/doc/ReleaseNotes4.12.md#parameterized-tests

[FIX] JUnit <4.12 compatiblity

---

basex-core/src/main/java/org/basex/query/func/fn/Ids.java
basex-core/src/test/java/org/basex/index/ValueIndexTest.java
basex-core/src/test/java/org/basex/query/simple/IdIdrefTest.java

Added parametrized test for fn:id and fn:idref with several combinations
of in-memory databases, updating and token indexes.
Fixed bug in fn:idref, which did not test whether the found node is the
desired document.
In case of `UPDINDEX=false` and `TOKENINDEX=true` there is still some issue left, as the test shows.

[ADD] Tests for fn:id/fn:idref, idref fix, open issue

---

.dockerignore
Dockerfile
README.md
basex-api/src/main/webapp/dba/Dockerfile

These commits:
- add a Dockerfile for `basexhttp`, including a `.dockerignore` file to prevent git history, programming APIs, the full test suite and other superfluous stuff of being added
- add a Dockerfile for the DBA, also providing an example on Docker usage for RestXQ projects
- update the `README.md` (which is also used on the Docker Hub) with information on Docker usage
- move some headings in the slightly enlarged readme file to the third headings level, to unclutter sectioning a little bit
After merging, I'll register the builds `basex/basexhttp` and `basex/dba` on Docker hub and put together documentation in the Wiki.

Added Dockerimage for automatic builds of basexhttp, DBA

---

basex-core/src/main/java/org/basex/gui/layout/BaseXKeys.java

From [KeyEvent docs](https://docs.oracle.com/javase/7/docs/api/java/awt/event/KeyEvent.html#VK_QUOTE):
> For key typed events, the getKeyCode method always returns VK_UNDEFINED.
> Not all keyboards or systems are capable of generating all virtual key codes. No attempt is made in Java to generate these keys artificially.
When I press `"` key the `KeyEvent e` returns `e.getKeyCode() == VK_UNDEFINED` and `e.getKeyChar() == '"'` also `BaseXKeys` returns `NEXTPAGE.is(e) == true` which is false.
`NEXTPAGE` is defined as `NEXTPAGE(NO_MOD, VK_PAGE_DOWN, SHIFT)` so `e.getKeyChar()` should never be compared to `VK_PAGE_DOWN`.
There could be one problem with this fix: `GOBACK2(VK_BACK_SPACE, NO_MOD)` sets `key = NO_MOD`, which equals to `key = 0`.

fix handling of undefined key events

---

.dockerignore
Dockerfile

Up to now, the Dockerfile copied an instance of the `web.xml` file from the ressources folder into the image. This one is not available in git, though -- resulting in the build process working fine locally, but breaking on the Docker hub.
This commit should fix image creation.

[FIX] Install web.xml in Docker image

---

Dockerfile
README.md

I would have preferred "nightly" as a Docker Hub tag, but we should also have "latest" and the Docker Hub merges branches resulting in different tags, deleting one of them.
The EVENT port 1985 was removed already, don't expose it any more.

[MIN] Docker: latest instead of nightly, remove EVENT port

---

basex-core/src/main/java/org/basex/gui/dialog/DialogAbout.java
basex-core/src/main/java/org/basex/gui/dialog/DialogEdit.java
basex-core/src/main/java/org/basex/gui/dialog/DialogExport.java
basex-core/src/main/java/org/basex/gui/dialog/DialogInput.java
basex-core/src/main/java/org/basex/gui/dialog/DialogInsert.java
basex-core/src/main/java/org/basex/gui/dialog/DialogInstallURL.java
basex-core/src/main/java/org/basex/gui/dialog/DialogLine.java
basex-core/src/main/java/org/basex/gui/dialog/DialogManage.java
basex-core/src/main/java/org/basex/gui/dialog/DialogMem.java
basex-core/src/main/java/org/basex/gui/dialog/DialogMessage.java
basex-core/src/main/java/org/basex/gui/dialog/DialogNew.java
basex-core/src/main/java/org/basex/gui/dialog/DialogPackages.java
basex-core/src/main/java/org/basex/gui/dialog/DialogPass.java
basex-core/src/main/java/org/basex/gui/dialog/DialogPrefs.java
basex-core/src/main/java/org/basex/gui/dialog/DialogProps.java
basex-core/src/main/java/org/basex/gui/dialog/DialogSort.java
basex-core/src/main/java/org/basex/gui/layout/BaseXDialog.java

I am experiencing problems when the main screen of GUI is located on the second screen.
The overriden `setLocation` is always limiting dialog windows to the primary screen dimensions.
I looked around the code and noticed that this method is probably defined because of some special dialog windows that get the location adjusted in relative to the main window.
I renamed `setLocation` to `setLocationWithinScreen` to explicitly mention it's function and to disable the override that was called by the superclass.
I overloaded `finish` method to clearly separate the cases that adjust location and cases that do not. Hopefully, this will make it easier for others to find the exact cases where dialog location is adjusted.
In my opinion, `setLocationWithinScreen` is still broken and should be updated …

Multiscreen setup

---

basex-api/src/main/webapp/dba/Dockerfile

DBA Dockerfile was not changed from the `nightly` to the `latest` tag yet, resulting in failed builds.

[MIN] Base DBA Docker image on basex/basexhttp:latest

---

Dockerfile

The upstream maven Docker image copies some files into the Maven config
directory during container startup, to fix some issues for images using
Maven at container runtime (see carlossg/docker-maven#11).
This broke startup for child images that do not run as root user (we're
adding a basex user). The same issue was described in
carlossg/docker-maven#14.
Resolves #1345, replaces #1346.

[FIX] Dockerfile: set m2 config directory

---

basex-core/src/main/java/org/basex/util/http/HttpClient.java
basex-core/src/main/java/org/basex/util/http/HttpPayload.java

Hi,
I was trying to build BaseX locally (using OpenJDK 8) and I've bumped into the following maven build error:
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project basex: Compilation failure: Compilation failure:
[ERROR] /home/user/sources/basex/basex-core/src/main/java/org/basex/util/http/HttpPayload.java:[184,28] reference to Base64 is ambiguous
[ERROR] both class org.basex.util.Base64 in org.basex.util and class java.util.Base64 in java.util match
[ERROR] /home/user/sources/basex/basex-core/src/main/java/org/basex/util/http/HttpClient.java:[262,22] reference to Base64 is ambiguous
[ERROR] both class org.basex.util.Base64 in org.basex.util …

improved consistency of Base64 class name usage (using full class name)

---

basex-core/src/main/java/org/basex/util/http/HttpClient.java

Right now, the timeout only sets the connect timeout that is active
while a connection is established, but not the read timeout while
waiting for a response.
The EXPath HTTP Client Module specification does not clearly state the
semantics of the parameter "timeout", but if the read timeout is not
considered in the implementation, a send-request() may hang forever
even though a timeout parameter has been provided.

proposed change for timeout in http:send-request()

---

basex-core/src/main/java/org/basex/query/func/crypto/CryptoHmac.java

Currently `crypto:hmac()` only allows for strings to be the key.
In some circumstances it might be necessary to use sequences of bytes as a key, that do not necessarily resemble a valid string in any encoding.
The proposed change does not change the behaviour in case `$key` is of type `xs:string`.
```xquery
crypto:hmac("foo", "bar", "md5") eq
crypto:hmac("foo", xs:base64Binary("YmFy"), "md5")
```

[ADD] crypto:hmac() allow bytestream as key

---

README.md

The `README.md` file has some minor markdown syntax issues, which result in a broken link on the Docker hub (#1448).

[MIN] Fixed markdown syntax issues in README (fixes #1448)

---

basex-core/src/main/java/org/basex/query/func/sql/SqlExecute.java
basex-core/src/main/java/org/basex/query/func/sql/SqlExecutePrepared.java

Return affected records on an update/insert/delete statement
Add Support for SQLXML type as binding type
Add Workaround for Oracle ORA-00904 on parsing VALID update statement

[MOD] Report Updated, Support SQLXML as binding, workaround for ORA

---

basex-api/.settings/checkstyle.xml
basex-core/.settings/checkstyle.xml
basex-examples/.settings/checkstyle.xml
basex-tests/.settings/checkstyle.xml

Running `mvn checkstyle:checkstyle` currently crashes because the configuration files have the module `StrictDuplicateCode` which is outdated. This PR removes the outdated module from the configuration files so that `mvn checkstyle:checkstyle` now does not crash.

Removed outdated Checkstyle module

---

basex-core/pom.xml
basex-core/src/main/java/org/basex/gui/GUIInput.java
basex-core/src/main/java/org/basex/gui/layout/BaseXCombo.java
basex-core/src/main/java/org/basex/gui/view/plot/PlotView.java
basex-core/src/main/java/org/basex/query/QueryContext.java
basex-core/src/main/java/org/basex/query/func/crypto/MyKeySelector.java
basex-core/src/main/java/org/basex/query/func/inspect/Inspect.java
basex-core/src/main/java/org/basex/query/func/xquery/XQueryParse.java
pom.xml

In Java 9, to be released in 30 days, some of basex ceases to compile or work:
* `java.lang.Module` has been added, causing star imports of classes named `Module` to fail: fixed by adding explicit imports.
* swing's `BasicComboPopup` constructor type has been changed. This is probably a JDK bug, but it's probably a bit late to fix it.
* An unchecked cast has become invalid, replaced with wildcards.
* A single test depends on some JAXB implementation, which has been removed from the JDK in 9. I've added one from Maven Central, at `test` scope. The state of JAXB implementations in Maven is a bit of a disaster. I doubt the test cares about a specific implementation; it's a very small use. Maybe there are some parts of the application which need these jars not a test scope? I don't know how …

Fix compilation with Java 9

---

basex-core/src/main/java/org/basex/query/func/sql/SqlExecutePrepared.java

An other oracle exception for a valid statement was thrown. So we changed it to ignore any oracle exception of getParameterMetaData.

[FIX] sqlExecutePrepared. Disable all oracle exceptions

---

basex-core/src/main/java/org/basex/query/func/sql/SqlExecute.java

Hi,
in case of an Oracle CLOB column only a "pointer"-value will returned by toString. 
So here some special handling for clobs is need. Beside Clob.getSubString also RecordSet.getString() will work in this Situation. But we followed the way as xmltype was handled here.
BTW: In case of execute-prepared big clob works fine, because the PreparedStatement.setString the counterpart of RecordSet.getString is used.
Best Regards
Jan

[MOD] add clob handling

---

basex-api/src/main/c/basexdbc.c
basex-api/src/main/c/basexdbc.h
basex-api/src/main/c/md5.h
basex-api/src/main/c/readstring.h

updated C API, so it works with v8.0+ of basex
this was tested with the example code and worked
should also work with older versions
and I have extern "C"'d the headers so this API
can be compiled with a c or c++ compiler

updated C API for newer authentication method

---

basex-core/src/main/java/org/basex/core/StaticOptions.java
basex-core/src/main/java/org/basex/io/IOUrl.java

as discussed in email exchange a patch for separating lax hostname verification from igrnoring certs altogether in HTTPS.

Ignorehostnameverification

---

basex-core/etc/basex
basex-core/etc/basexgui

See discussion:
https://unix.stackexchange.com/questions/279024/reason-for-exec-in-wrapper-scripts

[MOD] Use exec for all wrapper scripts.

---

basex-api/src/main/c/basexdbc.c
basex-api/src/main/c/example.c
basex-api/src/main/java/org/expath/ns/GeoErrors.java
basex-api/src/main/qt/example.xml
basex-core/src/test/java/org/basex/core/locks/LockingTest.java
basex-core/src/test/java/org/basex/index/ValueIndexTest.java
basex-core/src/test/resources/xqdoc.xsd

All of them were found by codespell.
Signed-off-by: Stefan Weil <sw@weilnetz.de>

Fix some typos in comments and messages

---

basex-api/src/main/c/basexdbc.c
basex-api/src/main/c/md5.c

Changes to work with type changes in newer version of openssl v1.1.0
- also compatible with older openssl v1.0.1
- this has been tested and works
- this newer version of openssl/crytpo library is installed on latest Ubuntu 18.04 LTS

changes for latest version of openssl

---

basex-core/src/main/java/org/basex/BaseXGUI.java
basex-core/src/main/java/org/basex/gui/GUIMacOS.java
basex-core/src/main/java/org/basex/gui/GUIMacOSX.java

Move Apple specific system properties to OSX classes.
Set useScreenMenuBar property for all JDKs.

macOS: Adjust apple system property

---

basex-api/src/main/webapp/dba/users/user-create.xqm
basex-api/src/main/webapp/dba/users/user.xqm

Fixed typo on login screen where 'Passsword' should be spelled 'Password'

Fixed Passsword typo

---

basex-api/src/main/java/org/basex/http/restxq/RestXqWadl.java

In the wadl generated by the `rest:wadl()` function, we noticed that the `wadl:resources/@base` contains redundant prefix that clashed with the `wadl:resource/@path`. This issue emerged while importing the resulting wadl into tools such as Postman. The proposed pull request should fix it in all cases, including deployment in application containers such as Tomcat (where there is a context path too).

Corrected wadl:resources/@base in RestXqWadl

---

basex-core/src/main/java/org/basex/gui/GUIMacOSX9.java

Refactoring in
https://github.com/BaseXdb/basex/commit/aad721d3#diff-a92349d39f7a7491805f1a4856fd1aa8R31
led to method invocation using a class reference where an object is required.
```
final Class<?> d = Desktop.getDesktop().getClass();
d.getDeclaredMethod("setAboutHandler", aboutHandler).invoke(d, proxy);
^- class                                                    ^- class (object required)
```

[FIX] Reenables 'About' & 'Preferences' on macOS w/ Java9 or greater

---

basex-core/src/main/java/org/basex/io/IO.java

I hope this is the only place that it needs to be added. (IDML files are Zip archives.)
If this is so, then this will fix #1758

add '.idml'

---

basex-api/src/main/php/AddExample.php
basex-api/src/main/php/BaseXClient.php
basex-api/src/main/php/BaseXClient/BaseXException.php
basex-api/src/main/php/BaseXClient/Exception.php
basex-api/src/main/php/BaseXClient/Query.php
basex-api/src/main/php/BaseXClient/Session.php
basex-api/src/main/php/CreateExample.php
basex-api/src/main/php/Example.php
basex-api/src/main/php/QueryBindExample.php
basex-api/src/main/php/QueryExample.php
basex-api/src/main/php/load.php

Code of the PHP client has to be modified for use in modern PHP projects, so I tried to fix this.
* directory structure adjusted with [PSR-4 autoloading](https://www.php-fig.org/psr/psr-4/) in mind, namespace added
-- i.e. the code as is does not use autoloading, but the `basex-api/src/main/php/BaseXClient` can be copy-pasted to a project with PSR-4 autoloading enabled and with a small bit of configuration in `composer.json` will work fine
Then I added some more improvements and updated some of the most archaic code features, while trying not to break compatibility with "reasonably old" outdated PHP versions.
* code style according to the [PSR-2](https://www.php-fig.org/psr/psr-2/) community standard enforced by [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)
* various code …

Refactor PHP client

---

basex-api/src/main/webapp/dba/databases/resources/db-query.xqm

We've found out (but not clearly identified) that with some combinations of browsers/proxies the body is not an empty string "" but rather an empty sequence. This is causing error when opening the database view of the dba. ("_Request body must be xs:string, supplied ()_")
We propose to make the query parameter optional.

Signature resilient to missing query

---

basex-core/src/main/java/org/basex/gui/dialog/DialogBindings.java

Change tab traversal order of the fields on the Bindings form so the text edit fields are traversed in rows instead of columns

Fix the Bindings dialog tab order

---

basex-core/src/main/java/org/basex/query/value/item/QNm.java

In EQNAME the closing brace also needs to be escaped.
Found out while using BaseX in android which gave a Pattern syntax error

fix in EQNAME regexp

---

basex-core/src/main/java/org/basex/io/IO.java
basex-core/src/main/java/org/basex/io/IOUrl.java
basex-core/src/main/java/org/basex/query/util/pkg/ModuleLoader.java
basex-core/src/main/java/org/basex/util/Prop.java

While trying to use BaseX in an application that is packaged as a fat jar, I found a few problems:
- Prop.applicationDir assumes that it is passed a file URL, which in this setup does not hold for Prop.LOCATION (which is something like "rsrc:basex-10.5-SNAPSHOT.jar"). This causes a FileSystemNotFoundException stack to be logged
- ModuleLoader.close closes the classloader when it is an URLClassLoader. However in this setup, the default classloader is an URLClassLoader and it must not be closed
- an XQuery module URL, in this setup, might be something like "jar:rsrc:xquery-module-test-plain.jar!/m0.xqm". This however not accepted by IOURL.isValid, because it insists on a '/' character following the protocol
- IOURL.inputStream use an HTTP connection, which does not work for jar URLs. For …

Allow running BaseX from a fat jar

---

basex-core/src/main/java/org/basex/io/parse/xml/XmlParser.java

Thanks for your effort maintaining this library :)
In version 9.1 [this method](https://github.com/BaseXdb/basex/blob/9.1/basex-core/src/main/java/org/basex/io/parse/xml/XmlParser.java#L58) was added which cannot be configured safely to prevent XXE.
Regardless of the configured `dtd` bool, without control over the `external-general-entities` feature, external DTDs are evaluated leading to exploitation.
By my understanding of the library a user passing `false` to the `dtd` parameter would not want/expect external DTDs to be evaluated, therefore allowing the feature flag to be controlled by this method resolves the issue.

Fix XXE vulnerability in XmlParser.java

---

basex-core/src/main/java/org/basex/query/expr/Pos.java
basex-core/src/test/java/org/basex/query/ast/RewritingsTest.java

An XQuery positional filter for the last one or two elements of a sequence,
```xquery
<a/>[position() >= last() - 1]
```
failed with this result, when there is just a single item in the context:
```
[FOAR0002] Value out of range: 9223372036854775807.
```
This is caused by [Pos.get](https://github.com/BaseXdb/basex/blob/73986c1c4c156eea9c236e432d011fd00162bd8d/basex-core/src/main/java/org/basex/query/expr/Pos.java#L71-L77) transforming the filter predicate to a range ending in Long.MAX_VALUE,
```java
case GE:
minMax = new Expr[] { ps, Int.MAX };
break;
case GT:
minMax = new Expr[] { new Arith(ii, type.instanceOf(AtomType.INTEGER) ? ps :
cc.function(Function.FLOOR, ii, ps), Int.ONE, Calc.PLUS).optimize(cc), Int.MAX };
break;
```
and …

Avoid long value overflow in position range

---

basex-core/src/test/java/org/basex/query/simple/SimpleTest.java

Sorry for coming back to this, but there are two test cases in [SimpleTest](https://github.com/BaseXdb/basex/blob/main/basex-core/src/test/java/org/basex/query/simple/SimpleTest.java#L230-L231) that are now causing out-of-memory after the recent changes with respect to ranges:
```java
{ "Limits 11", "0 to 9223372036854775807" },
{ "Limits 11", "-9223372036854775807 to 9223372036854775807" },
```
I guess these just have to go now.

Avoid OOME in SimpleTest 

---

basex-core/src/main/java/org/basex/query/expr/Typeswitch.java
basex-core/src/main/java/org/basex/query/expr/TypeswitchGroup.java
basex-core/src/test/java/org/basex/query/simple/SimpleTest.java

An XQuery typeswitch returned a wrong value, e.g.
```xquery
for $value in (0, 0.0)
return
typeswitch ($value)
case xs:integer return 'integer'
case xs:decimal return 'decimal'
default return 'neither'
```
returned `('decimal', 'decimal')`, where it should have been `('integer', 'decimal')`.
This is caused by [Typeswitch.optimize](https://github.com/BaseXdb/basex/blob/5e1ec7605d368aa214b3cf2e3865cf4b0ccd0443/basex-core/src/main/java/org/basex/query/expr/Typeswitch.java#L83-L89) selecting a branch based on the static type of the operand 
expression (in the example above, xs:decimal):
```java
// check if always the same branch will be evaluated
Expr expr = this;
// choose branch that can be statically determined
TypeswitchGroup tg = null;
for(final TypeswitchGroup group : groups) {
if(tg == …
```

Prevent typeswitch optimization from selecting supertype branches

---

basex-core/src/main/java/org/basex/io/serial/HTMLSerializer.java
basex-core/src/main/java/org/basex/io/serial/XHTMLSerializer.java
basex-core/src/test/java/org/basex/query/SerializerTest.java

When using (X)HTML serialization with `indent=yes`, some unwanted whitespace appeared in a `pre` element, and in rendered content. E.g.
```xml
<html><body><pre><u>test</u></pre></body></html>
```
was serialized as
```xml
<html>
<body>
<pre>
<u>test</u>
</pre>
</body>
</html>
```
While this OK with XML serialization, (X)HTML serialization must not modify whitespace inside of formatted elements, as specified in
* [6.1.4 XHTML Output Method: the indent and suppress-indentation Parameters](https://www.w3.org/TR/xslt-xquery-serialization-31/#XHTML_INDENT) 
* [7.4.3 HTML Output Method: the indent and suppress-indentation Parameters](https://www.w3.org/TR/xslt-xquery-serialization-31/#HTML_INDENT)
This fix overrides MarkupSerializer.indent in HTMLSerializer and XHTMLSerializer, in order to …

Suppress indentation inside of (X)HTML formatted elements

---

basex-core/src/main/java/org/basex/io/serial/HTMLSerializer.java
basex-core/src/main/java/org/basex/io/serial/MarkupSerializer.java
basex-core/src/main/java/org/basex/io/serial/Serializer.java
basex-core/src/main/java/org/basex/io/serial/XHTMLSerializer.java
basex-core/src/test/java/org/basex/query/SerializerTest.java

More unwanted whitespace was found using (X)HTML serialization with `indent=yes`. An example of this is
```xml
<html><style type="text/css"></style><body><p><a name="x"><b>X</b></a> <a name="y"><b>X</b></a></p></body></html>
```
As is, browsers show it as
But when serialized with `method=html` and `indent=yes`, it becomes
```html
<html>
<style type="text/css">
</style>
<body>
<p>
<a name="x">
<b>X</b>
</a>
<a name="y">
<b>X</b>
</a>
</p>
</body>
</html>
```
and browsers show it as
The difference in this case is caused by the indentation whitespace that was added between the closing tags for `b` and `a`. According to the serialization spec, that whitespace should not be there, because `a` and `b` are "inline" elements - see
* [6.1.4 XHTML Output Method: the indent and suppress-indentation …

Suppress indentation adjacent to (X)HTML inline elements

---

basex-core/src/main/java/org/basex/io/serial/Serializer.java
basex-core/src/test/java/org/basex/query/SerializerTest.java

After the recent changes of (X)HTML serialization for #2171, concerning inline elements, excess indentation whitespace could still be added following an empty tag of an inline element. This was caused by the empty tag not being remembered as the last closed tag.
This fix corrects the setting of `Serializer.closed` to that respect, and it extends HTML and XTHML serialization tests accordingly.

Do not add indentation whitespace following empty (X)HTML inline elements

---

basex-core/src/main/java/org/basex/io/out/EncoderOutput.java
basex-core/src/main/java/org/basex/io/out/NewlineOutput.java
basex-core/src/main/java/org/basex/io/out/PrintOutput.java
basex-core/src/main/java/org/basex/io/serial/HTMLSerializer.java
basex-core/src/main/java/org/basex/io/serial/MarkupSerializer.java
basex-core/src/main/java/org/basex/io/serial/SerializerOptions.java
basex-core/src/test/java/org/basex/query/SerializerTest.java

Here are the changes that implement #2174. A new serialization option is added to control indentation of attributes. The option name and the new layout are the same as in [HTML Tidy](https://api.html-tidy.org/tidy/quickref_5.8.0.html#indent-attributes):
- the name is `indent-attributes`, with a default value of `no`.
- the layout that is achieved by `indent-attributes=yes` puts the first attribute following the element name on the same line, while every subsequent attribute starts a new line, indented to align with the first attribute.
The order of attributes is unchanged. `indent-attributes` is ignored when processing serialization methods other than `xml`, `xhtml`, or `html`. It may not make much sense to use this option without using `indent=yes` as well, but the implementation here …

Add serialization option 'indent-attributes'

---

basex-core/src/main/java/org/basex/query/func/fn/FnInvisibleXml.java

`fn:invisible-xml` is dependent on the JVM's default encoding. This can be seen by running the following on Windows,
```sh
chcp 65001
java -Dfile.encoding=utf-8        org.basex.BaseX "invisible-xml('s: +#10D.')('')"
java -Dfile.encoding=windows-1252 org.basex.BaseX "invisible-xml('s: +#10D.')('')"
```
The first invocation correctly returns
```xml
<s>č</s>
```
while the second one comes up with
```xml
<s>?</s>
```
This is caused by a dependency of the default encoding in `org.nineml.coffeefilter.trees.StringTreeBuilder`. I have opened nineml/coffeefilter#82 for resolving it. Until it has been processed, this change provides a workaround.

Make fn:invisible-xml independent of default encoding

---

basex-core/src/main/java/org/basex/query/func/fn/FnInvisibleXml.java

Sorry, my fault. The invocation of `getTree` had left the `try` block, but it must stay in there to have `IxmlException` caught and handled with `IXML_RESULT_X`. Obviously I had not run the tests...

Move getTree invocation back into try block

---

pom.xml

Version `2.0.0` was released recently for both `CoffeeFilter` and `CoffeeGrinder`.

Bump CoffeeFilter and CoffeeGrinder to 2.0.0

---

basex-core/src/main/java/org/basex/util/hash/WeakTokenSet.java
basex-core/src/test/java/org/basex/util/WeakTokenSetTest.java

This is a unit test for WeakTokenSet. It creates some random strings and adds them to a WeakTokenSet. Then some (or even all) of them are removed, and it is verified that those removed have been garbage collected in the set's weak references, while the others are still present.
The test is repeated 8 times. It uses a random seed, thus there is a chance to test something different with each execution. Assertion failure messages contain the seed value, so the failure can be reproduced by installing that seed.

Add WeakTokenSetTest

---

basex-core/src/main/java/org/basex/io/IOUrl.java

The requirement of a slash following the URL scheme had been dropped for all URLs in 1e14f79 in order to allow `jar:` urls occurring when the code is packaged as a fat jar. This change reinstalls the previous state, except for `jar:` urls, which are still allowed without a slash.

Allow opaque URLs for jar: only (fixes BaseXdb/basex#2228)

---

basex-core/src/main/java/org/basex/query/util/regex/parse/RegExParser.java
basex-core/src/main/javacc/regex.jj
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java

Sorry for the stupid mistake, the previous change was possibly done too quickly. The lookahead token at the end of the charclass is BR_CLOSE, so this is what must be checked for.

Disallow BR_CLOSE at the end of a charRange (fixes #2240)

---

basex-core/src/main/java/org/basex/query/util/regex/BackRef.java
basex-core/src/main/java/org/basex/query/util/regex/Group.java
basex-core/src/main/java/org/basex/query/util/regex/Piece.java
basex-core/src/main/java/org/basex/query/util/regex/Quantifier.java
basex-core/src/main/java/org/basex/query/util/regex/parse/RegExParser.java
basex-core/src/main/javacc/regex.jj
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java

This PR contains three changes addressing three problems:
1. eb1394b0188025129021b6495018a1d334efbfaf: a literal dash was allowed in a regex when it followed a MultiCharEsc, violating the restriction that it is only allowed at the begin or end of its charGroup. An extra check has been added verifying this. This fixes tests p888-p891.
2. cce82a319f2d57a5bc97acf14360370acd2158cc: backrefs where not considered to match, when the corresponding group is optional and did not match anything - this is the JRE's regex engine's way of handling this. It was changed by making the group mandatory and wrapping its content in an optional non-capturing group. This fixes tests p295 and p303.
3. 8769b7db98d0449fb3ac57cb7a3e05530d7ab492: backrefs were not considered to match, when they are in a different …

Fixes for failing regex tests (fixes #2240)

---

basex-core/src/main/java/org/basex/build/xml/SAXWrapper.java
basex-core/src/main/java/org/basex/io/IO.java
basex-core/src/main/java/org/basex/io/IOContent.java
basex-core/src/test/java/org/basex/data/MemDataTest.java

Some time ago I was using a Java tool (can't remember what it was) that generated XML in a Java string starting with an XML declaration of
```xml
<?xml version="1.0" encoding="UTF-16"?>...
```
When passing that via `IO.get` to the `DBNode` constructor,
```java
new DBNode(IO.get(xml))
```
it failed with a parsing error, because the string is internally encoded in UTF-8, the resulting byte stream is then passed to the XML parser, which decodes it per the encoding from the XML declaration. At the time I had fixed this in the application by omitting the XML declaration, but later I realized that the same is reproducible by a query like
```xquery
parse-xml('<?xml version="1.0" encoding="utf-16"?><xml/>')
```
This PR is a proposal for fixing this, by making making `IOContent` supply a `Reader` …

Ignore encoding from XML declaration when parsing a String value

---

basex-core/src/main/java/org/basex/query/QueryError.java
basex-core/src/main/java/org/basex/query/func/Function.java
basex-core/src/main/java/org/basex/query/func/fn/FnInvisibleXml.java
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java
pom.xml

The [draft specification](https://qt4cg.org/pr/791/xpath-functions-40/Overview.html#func-invisible-xml) for `fn:invisible-xml` needs these changes in the implementation:
- an empty sequence for `$grammar` must use the Invisible XML specification grammar,
- the optional `$options` argument must be supported,
- errors codes must be `FOIX0001` and `FOIX0002`.

Adapt fn:invisible-xml to draft specification

---

basex-core/src/main/java/org/basex/query/util/format/FormatParser.java
basex-core/src/main/java/org/basex/query/util/format/FormatUtil.java
basex-core/src/main/java/org/basex/query/util/format/Formatter.java
basex-core/src/main/java/org/basex/query/util/format/IntFormat.java
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java
basex-core/src/test/java/org/basex/query/func/fn/FnFormatIntegerTest.java

Here are some changes of fn:format-integer, which will
- consider an explicit radix only if an `X` or `x` mandatory-digit-sign is present in the primary format token
- prevent separators from appearing in the result before any digits
- handle format pictures containing `X` or `x` mandatory-digit-signs, when an explicit radix is present.
They will fix these tests from qt4tests:
- format-integer-030
- format-integer-40-001
- format-integer-40-002
- format-integer-40-008
- format-integer-40-009
- format-integer-40-010
- format-integer-40-013
- format-integer-40-016
- format-integer-40-014
- format-integer-40-015

Fix 10 qt4tests test cases for fn:format-integer

---

basex-core/src/main/java/org/basex/query/util/format/Formatter.java
basex-core/src/main/java/org/basex/query/value/item/ADate.java
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java

These changes support IANA time zone names in the `$place` argument of `fn:format-date`, `fn:format-time`, and `fn:format-dateTime`, by adjusting the value to the given time zone before formatting. This is specified in the last paragraph of [9.8.4.8 The language, calendar, and place arguments](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#lang-cal-place).

Support IANA time zone names

---

basex-core/src/main/java/org/basex/query/util/collation/UCACollation.java

The comparison of collation elements has been improved, now respecting the collator's properties.
This fixes most of the QT4 test cases that failed after adding ICU4J to the classpath, in particular those with name prefixes
- compare
- fn-contains
- fn-ends-with
- fn-starts-with
- fn-substring-after
- fn-substring-before
- defaultcolldecl
- fo-test-fn-contains
- fo-test-fn-starts-with
- fo-test-fn-ends-with
- fo-test-fn-substring-before
- fo-test-fn-substring-after
Some with the following prefixed are still failing, I am still working on those:
- format-time
- UCA

Respect ICU collator properties while comparing collation elements

---

basex-core/src/main/java/org/basex/query/util/collation/UCAOptions.java

`alternate=blanked` is similar to `alternate=shifted`, however the differences must show up at `identical` level rather than at `quaternary` level, effectively making the set of `quaternary` differences empty. Combining it with `strength=quaternary` should do the same as `strength=tertiary`.
The ICU collator only has `strength` and `isShifted`. `blanked` must be represented by suppressing the `quaternary` level.
This fixes QT4 test case `compare-041`.

Suppress quaternary level for UCA collation with alternate=blanked

---

basex-core/src/main/java/org/basex/query/util/format/FormatterEN.java

QT4 tests `format-time-021` and `format-time-022` currently fail when ICU4J is on the classpath, because AM/PM indicators in mixed case are expected to be `Am` and `Pm`, but come out as `AM` and `PM`.
I think that the expectation is dubious - would anyone in real life ever want `Am`/`Pm`? The mixed-case form of AM/PM and era indicators in English should rather be `AM`, `PM`, and `BC`, `AD`.
Changing it this way will make those tests fail without ICU4J, too. For getting that fixed, we should add alternate results to [format-time.xml](https://github.com/qt4cg/qt4tests/blob/7e29d5fd0dcb4c732d838a9f2e51d92436756b72/fn/format-time.xml#L392-L416). If you agree, I will gladly add a corresponding PR to [qt4tests](https://github.com/qt4cg/qt4tests).

Improve mixed-case English AM/PM and era indicators

---

basex-core/src/main/java/org/basex/query/util/collation/BaseXCollationOptions.java
basex-core/src/main/java/org/basex/query/util/collation/Collation.java
basex-core/src/main/java/org/basex/query/util/collation/CollationOptions.java
basex-core/src/main/java/org/basex/query/util/collation/UCACollation.java
basex-core/src/main/java/org/basex/query/util/collation/UCAOptions.java
basex-core/src/test/java/org/basex/util/options/OptionsTest.java

These changes fix the test failures that came up after adding ICU4J to the classpath, in tests with name prefix `UCA`.
The failure count for those tests reduces to 1 without and to 3 with ICU4J. The remaining failures are
- `UCA-params-034`: Unknown function: `fn:collation-key`. This occurs in either variant.
- `UCA-reorder-codes-009`, `UCA-reorder-codes-010`: these occur **with** ICU4J, and IMO they trigger a bug in ICU4J when using `RuleBasedCollator.setReorderCodes`. I made some experiments by setting the codes in a more explicit fashion, but did not manage to get it working consistently. This might be the same bug that Saxon is referring to [in its documentation of `reorder`](https://www.saxonica.com/documentation12/index.html#!localization/unicode-collation-algorithm).

Allow unknown UCA option names and values when fallback is not "no"

---

basex-core/src/main/java/org/basex/query/QueryError.java
basex-core/src/main/java/org/basex/query/util/format/DateFormat.java
basex-core/src/main/java/org/basex/query/util/format/FormatParser.java
basex-core/src/main/java/org/basex/query/util/format/Formatter.java
basex-core/src/main/java/org/basex/query/util/format/IntFormat.java
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java

These changes fix 10 QT4 test cases with name prefix `millisecs` that used to fail before.

Fix millisecs tests

---

basex-core/src/main/java/org/basex/query/func/fn/FnAnalyzeString.java
basex-core/src/main/java/org/basex/query/func/fn/FnReplace.java
basex-core/src/main/java/org/basex/query/func/fn/RegEx.java
basex-core/src/main/java/org/basex/query/util/regex/parse/RegExParser.java
basex-core/src/main/javacc/regex.jj
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java
basex-core/src/test/java/org/basex/query/func/fn/RegexTest.java

These changes fix QT4 test case `analyzeString-017`. This requires calculation of the parent group of a regex group, for being able to decide where to put an empty match for some group within the result of `fn:analyze-string`.
The parent group could have been calculated while parsing the regex, however when using option `j`, this does not take place. So it was implemented by a separate scan of the Java regex. This however is only done when a group matches the empty string while processing the result of `fn:analyze-string`.
Member `groups` of `RegExp.RegExpr` has been dropped, because the same information is available from `Matcher.groupCount`. This change also enables proper handling of group references in `fn:replace` when using the `j` option (`groups` was not set in this case).

Add calculation of parent groups in regexes

---

pom.xml

1.3 brings a significant performance improvement and thread-safe parsing functions.

Update Markup Blitz dependency to 1.3

---

basex-core/src/main/java/org/basex/query/QueryParser.java
basex-core/src/main/java/org/basex/query/var/Var.java
basex-core/src/test/java/org/basex/query/ast/RewritingsTest.java
basex-core/src/test/java/org/basex/query/expr/GFLWORTest.java

These changes add coercion for variable bindings with an explicit type. The functionality was alread present in the `Var` class, it just needed to be activated in case there is a type definition. The `param` flag of `Var` was unused, so it has been removed.

Add support for coercion of typed variable bindings

---

basex-core/src/main/java/org/basex/query/value/type/SeqType.java
basex-core/src/test/java/org/basex/query/ast/FuncItemTest.java

In `SeqType.coerce` coercion is skipped, if an instance test succeeds. But in case of a function item, this also skips coercion of the arguments, which may still be necessary.
This change calculates whether there is any non-`item()*` argument, and enforces coercion in case there is.
The corresponding QT4 test cases are `enum-024` and `FunctionCall-058`, these now produce the expected result.

Make sure FItem argument coercion is not skipped

---

basex-core/src/test/java/org/basex/query/func/FnModuleTest.java
pom.xml

1.4 implements the newly defined line ending normalization, and some bug fixes.

Update Markup Blitz dependency to 1.4

---

basex-core/src/main/java/org/basex/query/func/array/ArrayGet.java
basex-core/src/main/java/org/basex/query/value/array/XQArray.java
basex-core/src/test/java/org/basex/query/expr/ArrayTest.java

Per XQuery 4, the different forms of accessing an array element, by
- using the array as a function item,
- `array:get`, and
- the lookup operator `?`,
are all subject to the coercion rules with respect to the array index.
This change invokes `SeqType.coerce` on the key from within `XQArray.getInternal`.
The corresponding QT4 test cases are `Lookup-019a`, `Lookup-119a`, and `UnaryLookup-019a`.

Add coercion for array lookup key

---

basex-core/src/main/java/org/basex/query/value/item/FItem.java
basex-core/src/main/java/org/basex/query/value/type/SeqType.java
basex-core/src/test/java/org/basex/query/ast/FuncItemTest.java

Function coercion of a map or array item is currently skipped, when the `funcType` of the item passes an instance test for the required function type. This however preserves its array or map identity, keeping it a suitable argument for the lookup operator, which it should not be. See qt4cg/qt4tests#109.
This change makes sure that non-`FuncItem`s are processed by `FItem.coerceTo` to actually return a `FuncItem`, when the required type is a `FuncType`. When coercing to `function(*)`, the item's `funcType` is used instead, in order to avoid special handling that would be necessary, because there are no required `argTypes`.
The corresponding QT4 test case is `MapTest-058a`.

Coerce maps and arrays to FuncItem

---

basex-core/src/main/java/org/basex/query/QueryParser.java
basex-core/src/main/java/org/basex/query/func/Closure.java
basex-core/src/main/java/org/basex/query/func/Functions.java
basex-core/src/main/java/org/basex/query/func/PartFunc.java
basex-core/src/test/java/org/basex/query/ast/FuncItemTest.java

The support for calling user-defined functions needs to be extended by
- handling keyword arguments,
- establishing the correct order of parameters of partially evaluated functions. This may deviate from the order in the target function when placeholders are used for keyword arguments.
This change 
- adds a call to `prepareArgs` to `Functions.dynamic`, in order to integrate keyword arguments into the positional argument list.
- calculates a permutation of placeholder ordinals, mapping the i-th placeholder in the integrated positional argument list (for the target function) to its position in the parameter list of the partially applied function,
- propagates the type to the parameter variable, in order to enable item coercion,
- disallows keyword arguments in dynamic function calls during …

Extend support for keyword args and placeholders

---

basex-core/src/main/java/org/basex/query/QueryParser.java
basex-core/src/main/java/org/basex/query/expr/path/Test.java
basex-core/src/main/java/org/basex/query/expr/path/UnionTest.java
basex-core/src/test/java/org/basex/query/ast/RewritingsTest.java
basex-core/src/test/java/org/basex/query/expr/PathTest.java

These changes add support for the `UnionNodeTest` grammar rule and maps it to a `UnionTest` instance, by also lifting the restriction that a `UnionTest` combines only tests with the a common node type. Instead of that common type, the `UnionTest`'s type is now set to the union of the types of the combined tests.
This fixes all of the remaining QT4 test cases with name prefix `UnionNodeTest`.

Add support for UnionNodeTest

---

basex-core/src/main/java/org/basex/query/QueryError.java
basex-core/src/main/java/org/basex/query/QueryParser.java
basex-core/src/main/java/org/basex/query/QueryText.java
basex-core/src/main/java/org/basex/query/value/map/XQMap.java
basex-core/src/main/java/org/basex/query/value/type/FuncType.java
basex-core/src/main/java/org/basex/query/value/type/MapType.java
basex-core/src/main/java/org/basex/query/value/type/RecordType.java
basex-core/src/main/java/org/basex/query/value/type/SeqType.java
basex-core/src/main/java/org/basex/query/value/type/Type.java
basex-core/src/test/java/org/basex/query/SeqTypeTest.java
basex-core/src/test/java/org/basex/query/simple/TypeTest.java

These changes provide the implementation of [RecordTest](https://qt4cg.org/specifications/xquery-40/xquery-40.html#id-record-test). This accomplished by adding a new class `RecordType extends MapType`.
This fixes 20 QT4 test cases with prefixes
- `array-members`
- `DynamicFunctionCall-R`
- `RecordTest`
- `Keywords-map-pair`
- `Keywords-array-members`
There are more test cases involving `RecordTest`s that are still failing. Those require coercion for records, which is not yet implemented.

Add support for RecordTest

---

basex-core/src/main/java/org/basex/query/value/map/XQMap.java
basex-core/src/main/java/org/basex/query/value/type/RecordType.java
basex-core/src/main/java/org/basex/query/value/type/SeqType.java

These changes build on last week's #2317, adding a naive implementation of coercion for `RecordTest`s. 
This fixes 29 test cases with prefixes
- `choice-type-156`
- `RecordTest-010`
- `DynamicFunctionCall-R-`

Add coercion for RecordTests

---

basex-core/src/main/java/org/basex/query/func/PartFunc.java

As discussed in qt4cg/qt4tests#148, coercion of explicit parameters is part of the process of constructing the function item, that results from partial function application.
This change thus adds coercion to `PartFunc.item`.
This causes some type errors to be detected earlier, fixing QT4 test cases
- `FunctionCall-422`
- `xqhof40`
- `xqhof41`

Add coercion for explicit parameters of partially applied function

---

basex-core/src/main/java/org/basex/query/QueryError.java
basex-core/src/main/java/org/basex/query/QueryParser.java
basex-core/src/main/java/org/basex/query/QueryText.java
basex-core/src/main/java/org/basex/query/scope/AModule.java
basex-core/src/test/java/org/basex/query/expr/MixedTest.java
basex-core/src/test/resources/hello.xqm

This change adds support for [Item Type Declarations](https://qt4cg.org/specifications/xquery-40/xquery-40.html#id-item-type-declaration), implementing them as aliases for the defined item type, and substituting each type reference with the definition during parser execution.
This does not yet take care of the spec changes in qt4cg/qtspecs#1355, nor does it include support yet for recursive record types.

Add support for item type declarations

---

basex-core/src/main/java/org/basex/query/util/regex/parse/RegExLexer.java
basex-core/src/main/java/org/basex/query/util/regex/parse/RegExParser.java
basex-core/src/main/javacc/regex.jj
basex-core/src/test/java/org/basex/query/func/fn/RegexTest.java

`RegexLexer` was using a single static instance `EOF_TOKEN` whenever reaching the end of input. However the state of a `Token` comprises the `next` member, which `RegexParser` uses to set up a linked list of tokens. This could lead to `EOF_TOKEN` being linked to itself, creating an endless list, when `RegexLexer.getNextToken` was called again after the end had already been noticed.
Usually this does not happen, but the code in `RegexParser.charRange` does not consider `EOF`, which may lead to an extra token being acquired.
These changes remove `RegexLexer.EOF_TOKEN`, and add extra EOF-checking to `RegexParser.charRange`.

Avoid reusing the EOF token (fixes BaseXdb/basex#2328)

---

basex-core/src/main/java/org/basex/query/QueryContext.java
basex-core/src/main/java/org/basex/query/QueryError.java
basex-core/src/main/java/org/basex/query/QueryParser.java
basex-core/src/main/java/org/basex/query/func/Functions.java
basex-core/src/main/java/org/basex/query/func/StaticFuncCall.java
basex-core/src/main/java/org/basex/query/func/StaticFuncs.java
basex-core/src/main/java/org/basex/query/func/fn/FnFunctionLookup.java
basex-core/src/main/java/org/basex/query/func/inspect/InspectFunctions.java
basex-core/src/main/java/org/basex/query/util/parse/LocalVars.java
basex-core/src/main/java/org/basex/query/var/StaticVarRef.java
basex-core/src/main/java/org/basex/query/var/Variables.java
basex-core/src/test/java/org/basex/query/ModuleTest.java

This change fixes 3 problems:
- functions from a different module that is not directly imported are no longer visible (this fixes #2048),
- variables from a different module that is not directly imported are no longer visible,
- public types from a directly imported module are now visible, even if the module was imported somewhere else before (this fixes a bug in the original implementation of type imports).
For functions and variables, a `hasImport` flag is introduced, that serves for detecting the absence of a required module import.
For getting the type import right, `QueryContext` now has a new member `libs`, that provides the `LibraryModule` holding the declared public types.

Fix module import with respect to functions, variables, and types (fixes #2048)

---

basex-core/src/main/java/org/basex/query/value/type/SeqType.java

The recent commit ba616c118c965d4df5600a44e06c2ab1ed335243 has introduced coercion to `MapType`. However this currently hides coercion to `RecordType`, because it is checked before the latter and succeeds for `RecordType`, that being a subclass of `MapType`.
This fixes `RecordTest.recRec`.

Fix coercion to RecordType

---

pom.xml

Markup Blitz 1.5 is a bugfix release.

Update markup-blitz dependency to 1.5

---

basex-core/src/main/java/org/basex/query/QueryParser.java
basex-core/src/main/java/org/basex/query/expr/path/NameTest.java
basex-core/src/main/java/org/basex/query/expr/path/UnionTest.java
basex-core/src/main/java/org/basex/query/func/Closure.java
basex-core/src/main/java/org/basex/query/value/item/QNm.java
basex-core/src/main/java/org/basex/query/value/type/ChoiceItemType.java
basex-core/src/main/java/org/basex/query/value/type/SeqType.java
basex-core/src/test/java/org/basex/query/simple/TypeTest.java

The QT4 `subtyping` tests have reported a number of failures that called for these fixes:
- type errors were reported while pre-evaluating `Closure`s at compile time for a function body that is never executed by a query. Reporting them made all QT4 test cases with prefix `subtyping` fail with type errors, because they use a construct similar to this:
```xquery
declare variable $var as item()* external := '';
function() as xs:integer {$var} instance of function() as xs:decimal
```
- `element(p1:a)` was incorrectly not considered an instance of `element(p1:*)`
- `element(p1:*|p2:*)` was incorrectly considered an instance of  `element(p1:*)`
- `element(a|b)` was incorrectly not considered an instance of  `element(*:a|*:b)`
- `element(a|b|c)` was incorrectly considered an instance of …

Fix instance tests for wildcard nametests, union nodetests, and choice item types

---

basex-core/src/main/java/org/basex/query/func/fn/FnLoadXQueryModule.java
basex-core/src/main/java/org/basex/query/var/StaticVar.java
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java

This change makes `fn:load-xquery-module` load a repository module, when there is no `content` or `location-hints` option.
Also it catches any unknown exceptions from evaluating variable values in `FnLoadXQueryModule` and translates them to  a `No value assigned to ...` error message. This is for handling `%basex:lazy` external variables without a defined value.

Support loading of repository modules via `fn:load-xquery-module`

---

basex-core/src/main/java/org/basex/query/QueryParser.java

In method `arrow`, a variable `$item` is created, which is never added to a `VarScope`. This causes its `slot` member to stick to the initial `-1` value and causes the AIOOBE reported in #2359.

Resolved unscoped variable with `localVars`

---

basex-core/src/main/java/org/basex/build/html/HtmlParser.java

`HtmlParser.Parser.ensureAvailable(String, byte[], InputInfo)` is called from a `HtmlParser.Parser.NU`, so it must not be declared as `private`.

Fix compile problems in `HtmlParser`

---

basex-core/src/main/java/org/basex/build/html/HtmlOptions.java
basex-core/src/main/java/org/basex/build/html/HtmlParser.java
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java

The only purpose of TagSoup options `html` and `method` is instructing TagSoup's serializer to generate HTML instead of XML. However HTML as an ouptut from TagSoup cannot be processed afterwards.
Thus these options are no longer supported with these changes. Rather the valid values of `HtmlOption.METHOD` now are `tagsoup` and `nu` for selecting the HTML parser to be used.

Remove support for TagSoup options `html` and `method`

---

.github/workflows/build.yml

This adds a simple GitHub workflow for running `mvn install` upon pushing to the main branch or creating a PR, or when triggered manually.

Add GitHub action to build and test upon push or PR

---

.github/workflows/build.yml

In my fork, I saw a build action hanging for more than 15 minutes after a test failure ([13028904697/job/36343594493](https://github.com/GuntherRademacher/basex/actions/runs/13028904697/job/36343594493)). So I am adding a job timeout of 10 minutes here.
Also adding dependency caching, which reduces the workflow's runtime by about 20 seconds.

Add timeout and dependency cache to build workflow

---

basex-core/src/test/java/org/basex/query/func/FnModuleTest.java
pom.xml

[1.6](https://github.com/GuntherRademacher/markup-blitz/releases/tag/1.6) is a bugfix release.

Update to markup-blitz 1.6

---

.github/workflows/build.yml

Coincidentally `v3` of the actions used in the build workflow went out of service today, which caused a [recent execution](https://github.com/BaseXdb/basex/actions/runs/13057309382) to fail. So we need to update to `v4`.

Update workflow action versions

---

basex-core/src/main/java/org/basex/io/parse/csv/CsvConverter.java
basex-core/src/main/java/org/basex/io/parse/csv/CsvParser.java
basex-core/src/main/java/org/basex/io/parse/csv/CsvW3Converter.java
basex-core/src/main/java/org/basex/io/parse/csv/CsvW3XmlConverter.java
basex-core/src/main/java/org/basex/query/func/fn/ParseCsv.java
basex-core/src/test/java/org/basex/query/func/CsvModuleTest.java

After a recent change, it was no longer possible to use `'yes'`/`'no'` or `'1'`/`'0'` instead of `true()`/`false()` as values of the `header` option of functions in the CSV module.
These changes restore this capability. In addition, they also support explicit column names in the `header` option, except for single strings with one of the above values.

CSV module: restore 'yes'/'no' values for header option, handle explicit column names

---

basex-core/src/main/java/org/basex/query/func/Function.java
basex-core/src/main/java/org/basex/query/func/fn/FnHtmlDoc.java
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java

This change adds `fn:html-doc($source as xs:string?, $options as map(*) := {})`.
The first parameter was named `$source` to be consistent with `fn:doc` and `fn:json-doc`.

Add function fn:html-doc

---

basex-core/src/main/java/org/basex/build/html/HtmlParser.java
basex-core/src/main/java/org/basex/query/func/html/HtmlParse.java
basex-core/src/main/java/org/basex/query/func/html/HtmlParser.java

This change will use Validator.nu as the default HTML parser, when TagSoup is unavailable, or fall back to XML parsing, if Validator.nu is unavailable, too.
When `HTMLPARSER` option `method` is used to override the default, then an error message is produced, if the specified parser is unavailable.

Use Validator.nu as default parser when TagSoup is unavailable

---

basex-core/src/main/java/org/basex/query/func/Function.java
basex-core/src/main/java/org/basex/query/func/StandardFunc.java
basex-core/src/main/java/org/basex/query/func/fn/FnAtomicTypeAnnotation.java
basex-core/src/main/java/org/basex/query/value/type/AtomType.java
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java

This change adds the implementation of `fn:atomic-type-annotation` along with some extra tests.
In contrast to the spec, as discussed in qt4cg/qtspecs#1851,
- the `variety` field of `fn:schema-type-record` is omitted for `xs:anySimpleType`,
- the `constructor` field of `fn:schema-type-record` is omitted for `xs:QName`.
Some QT4 tests for the function require the unsupported `typedData` feature. This has been addressed in qt4cg/qt4tests#213.

Add implementation of `fn:atomic-type-annotation`

---

basex-core/src/main/java/org/basex/query/func/Function.java
basex-core/src/main/java/org/basex/query/func/fn/FnAtomicTypeAnnotation.java
basex-core/src/main/java/org/basex/query/func/fn/FnNodeTypeAnnotation.java
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java

This change adds the implementation of `fn:node-type-annotation` and some tests for it.

Add implementation of  `fn:node-type-annotation`

---

basex-tests/src/main/java/org/basex/tests/w3c/QT3TS.java

In a recent change (6e599973864c5269d1a3ed69d3b172d23204a9e6), test result comparison was changed to run with `declare boundary-space preserve`. This was done after observing that tests [`parse-xml-421`](https://github.com/qt4cg/qt4tests/blob/87590dd60a281151c1dab4ef3f98d1e4a6eb1ac7/fn/parse-xml.xml#L299-L308) and [`parse-xml-fragment-421`](https://github.com/qt4cg/qt4tests/blob/87590dd60a281151c1dab4ef3f98d1e4a6eb1ac7/fn/parse-xml-fragment.xml#L334-L343) were successful regardless of whether option `strip-space` was implemented or not.
This has however caused 8 other tests to fail, because they depend on boundary-space being stripped while comparing results, e.g.
- [`ForExprType009`](https://github.com/qt4cg/qt4tests/blob/87590dd60a281151c1dab4ef3f98d1e4a6eb1ac7/prod/ForClause.xml#L1725-L …

Revert recent change with respect to boundary-space

---

basex-core/src/main/java/org/basex/query/func/Function.java
basex-core/src/main/java/org/basex/query/func/fn/FnApply.java
basex-core/src/main/java/org/basex/query/func/fn/FnPartialApply.java
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java

This change
- adds the implementation of `fn:partial-apply`,
- updates `fn:apply` to ignore excess function arguments.

Add implementation of `fn:partial-apply`, update `fn:apply`

---

basex-core/src/main/java/org/basex/query/func/archive/ArchiveRefresh.java

Since Java 13 there are two `FileSystems.newFileSystem` methods which accept a null second parameter. This makes a call with `null` ambiguous. See [https://errorprone.info/bugpattern/NewFileSystem].
The proposed change casts the null parameter to the intended type.

Java 13 compatibility for `FileSystems.newFileSystem`

---

basex-core/src/main/java/org/basex/io/IOUrl.java

Commit e92e650929722f016cb1c73adf7fcb842eff2036 does not yet solve the original problem that 83acbb74f9419d50a4c03c5793647d449b5577c1 was addressing, when the source is a remote URL. For example, 
```xquery
base-uri(doc('https://www.w3.org/TR/xml/'))
```
This still returns `https://www.w3.org/TR/xml/xml`. I had not added that to the tests to avoid the remote access. Even tried a catalog to resolve it locally, but that does not help, because then the local URI is returned.
I think that `single` must be set to `true` in `IOUrl` as well to fix this.

Fix `fn:base-uri` for remote URLs ending in a slash (follow-up to #2404)

---

basex-core/src/main/java/org/basex/query/value/type/SeqType.java
basex-core/src/test/java/org/basex/query/func/MapModuleTest.java

The spec says that record `fn:key-value-pair` is extensible, but its representation in `SeqType.PAIR` currently is not. This change makes it extensible and adds a test that requires extensibility. This also fixes QT4 test `map-of-pairs-011`.

Make record `fn:key-value-pair` extensible

---

basex-core/src/main/java/org/basex/query/func/fn/FnAnalyzeString.java
basex-core/src/main/java/org/basex/query/func/fn/FnMatches.java
basex-core/src/main/java/org/basex/query/func/fn/FnReplace.java
basex-core/src/main/java/org/basex/query/func/fn/FnTokenize.java
basex-core/src/main/java/org/basex/query/func/fn/RegExFn.java
basex-core/src/main/java/org/basex/query/util/regex/Escape.java
basex-core/src/main/java/org/basex/query/util/regex/LineBorder.java
basex-core/src/main/java/org/basex/query/util/regex/LookAround.java
basex-core/src/main/java/org/basex/query/util/regex/WordBoundary.java
basex-core/src/main/java/org/basex/query/util/regex/parse/RegExLexer.java
basex-core/src/main/java/org/basex/query/util/regex/parse/RegExParser.java
basex-core/src/main/java/org/basex/query/util/regex/parse/RegExParserConstants.java
basex-core/src/main/javacc/regex.jj
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java
basex-core/src/test/java/org/basex/query/func/fn/RegexTest.java

This change implements the following changes of regular expression handling
- word boundary assertions
- lookahead and lookbehind assertions
- representation of lookahead groups in `fn:analyze-string` results
- removal of matches-empty restriction for `fn:analyze-string`, `fn:tokenize`, `fn:replace`

Implement recent changes in regular expression handling

---

basex-core/src/main/java/org/basex/query/func/Function.java
basex-core/src/main/java/org/basex/query/func/fn/FnAtomicTypeAnnotation.java
basex-core/src/main/java/org/basex/query/func/fn/FnNodeTypeAnnotation.java
basex-core/src/main/java/org/basex/query/func/fn/FnSchemaType.java
basex-core/src/main/java/org/basex/query/value/type/ListType.java
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java

This change adds the implementation of `fn:schema-type`. 
The basic logic for creating `fn:schema-type-record` instances was already present in `FnAtomicTypeAnnotation`. 
It has been moved to new class `FnSchemaType`, which is now the base class of `FnAtomicTypeAnnotation` and `FnNodeTypeAnnotation`, and it was extended to additionally cover `AtomType.NUMERIC` and instances of `ListType`.

Implement `fn:schema-type`

---

basex-core/src/test/java/org/basex/query/func/FnModuleTest.java
pom.xml

[1.8](https://github.com/GuntherRademacher/markup-blitz/releases/tag/1.8) improves the usability of error messages.

Update to markup-blitz 1.8

---

basex-core/src/main/java/org/basex/query/func/fn/FnParseXml.java
basex-core/src/main/java/org/basex/query/func/fn/FnParseXmlFragment.java
basex-core/src/test/java/org/basex/core/CatalogTest.java
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java

As discussed - rather than individually allowing option `catalog`, `fn:parse-xml` now honors context option `CATALOG`. The documentation has already been adapted.

Remove option `catalog` from `fn:parse-xml`

---

basex-core/src/main/java/org/basex/gui/view/editor/EditorView.java
basex-core/src/main/java/org/basex/io/parse/json/JsonConverter.java
basex-core/src/main/java/org/basex/io/parse/json/JsonParser.java
basex-core/src/main/java/org/basex/query/QueryContext.java
basex-core/src/main/java/org/basex/query/QueryException.java
basex-core/src/main/java/org/basex/query/func/fn/ParseJson.java
basex-core/src/main/java/org/basex/util/InputInfo.java
basex-core/src/test/java/org/basex/io/parse/json/JsonParserTest.java
basex-core/src/test/java/org/basex/io/parse/json/JsonStringConverter.java
basex-core/src/test/java/org/basex/query/func/FnModuleTest.java

These changes make the JSON parser accept a `TextInput` in order to support streaming:
- `JsonParser` no longer derives from `InputParser`, but now has its own `consume` methods.
- the most recent 16 input code points are  buffered, for being able to make them available to error messages and to the `fallback` function.
- members `line` and `column` of `InputInfo` have been changed from `int` to `long`, in order to avoid overflows showing up in error messages.
This does not yet cover providing any progress info.

Support streaming in the JSON parser

---

basex-core/src/main/java/org/basex/io/serial/csv/CsvSerializer.java
basex-core/src/main/java/org/basex/io/serial/csv/CsvW3XmlSerializer.java
basex-core/src/test/java/org/basex/query/func/CsvModuleTest.java

`CscW3Serializer` called `record(headers)`, which resets `headers`, but `headers` was needed later on to verify the incoming column names. A bug in the name comparison logic (#2428) however was hiding this.
This change prevents `headers` to be reset by using a new signature of the `record` method, which provides control over resetting.

Prevent `CscW3Serializer` from resetting headers (fixes #2428)

---

basex-api/src/main/java/org/basex/http/webdav/WebDAVResponse.java

This PR addresses potential security vulnerability of cookies set in WebDAVResponse.java by explicitly setting:
- `HttpOnly = true`: prevents client-side scripts from accessing cookies
- `Secure = true`: ensures cookies are only sent over HTTPS
- `Path = "/"`: restricts cookies to the application root path
Appreciate time taken to review this, thanks!
References
https://cwe.mitre.org/data/definitions/1004.html

set HttpOnly, Secure, and Path attributes for cookies

---

basex-core/src/main/java/org/basex/query/expr/ALookup.java
basex-core/src/test/java/org/basex/query/expr/LookupTest.java

The current implementation incorrectly returns a result for
```xquery
[ 'a' ]??(1.1)
```

Use relabeling rather than just casting for deep lookup array keys

---

basex-core/src/test/java/org/basex/query/func/FnModuleTest.java

The new test for `fn:unparsed-binary` checks the exact size of a text file. The project however does not have a `.gitattributes` prescribing specific line endings, so these may be LF or CR-LF, depending on the environment. This change allows both variants.

Allow line endings of either LF or CR-LF in test for `fn:unparsed-binary`

---

basex-core/src/main/java/org/basex/io/parse/xml/XmlParser.java

This change 
- enforces the JDK's built-in XML-Parser by using `SAXParserFactory.newDefaultInstance`
- removes the temporary fix of not propagating the entity expansion limit in case it is being set to the JDK's default
Note: the spec of `entity-expansion-limit` says:
> if the value is zero, then entity expansion should if possible be disabled entirely, leading to a dynamic error if the input contains any entity references. A negative value should be interpreted as placing no limits on entity expansion.
This could be handled as speficied at this point by mapping 0 to -1 and negative values to 0, as was done somewhere in my original PR for the feature. @ChristianGruen, I guess you deliberately removed this, did you?

Use JDK's default SAXParserFactory

---

basex-core/src/main/java/org/basex/io/serial/SerializerOptions.java
basex-core/src/main/java/org/basex/io/serial/XHTMLSerializer.java
basex-core/src/test/java/org/basex/query/SerializerTest.java

The XHTML serializer currently does not honor serialization parameter `escape-uri-attributes` because of a bug in constructing the element-attribute pair for checking the set of URI attributes.
Also, the spec (even in [XQuery 3.1](https://www.w3.org/TR/xquery-31/#id-xq-static-context-components)) says that the default value of `escape-uri-attributes` should be `yes`.

Fix `escape-uri-attributes` for XHTML serializer

---

basex-core/src/main/java/org/basex/query/QueryParser.java
basex-core/src/test/java/org/basex/query/expr/AnnotationsTest.java

This adapts to recent grammar changes with respect to  `AnnotationValue`, `QNameLiteral`, and `MarkedNCName`.
It would have been possible to reuse `literal()` in `annotations(boolean)`, but I have preferred to keep it separate, as in the specification grammar.
This fixes 6 QT4-tests that are using whitespace in `QNameLiteral`s and `MarkedNCName`s:
- `K2-ComputeConAttr-64`
- `K2-ComputeConElem-19`
- `nscons-046`
- `K2-ComputeConPI-15`
- `Literals-40-925`
- `Literals-40-926`

Allow `QNameLiteral` as `AnnotationValue`, whitespace in `QNameLiteral` and `MarkedNCName`

---

basex-core/src/main/java/org/basex/query/QueryParser.java
basex-core/src/test/java/org/basex/query/expr/GFLWORTest.java

In method `letStructBinding`, a variable is created to hold the structure, which is never added to a `VarScope`. This causes its `slot` member to stick to the initial `-1` value and causes the AIOOBE reported in https://github.com/BaseXdb/basex/issues/2452.

Resolve unscoped variable with `localVars`

---

basex-tests/src/main/java/org/basex/tests/w3c/QT3TS.java

There are currently 4 tests for `fn:unparsed-binary` that fail on a resource that cannot be resolved. These tests can be made to work by having the test URI resolver handle these resources.

Use URI resolver for test resources

---

basex-core/src/main/java/org/basex/query/value/map/XQMap.java
basex-core/src/main/java/org/basex/query/value/map/XQRecordMap.java

As reported by [Andreas Hengsbach on basex-talk](https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg16267.html), a `ClassCastException` may occur when `inspect:argument` is called with a map argument, e.g.
```xquery
map {
'username' : "aaa",
'password' : "bbb",
'grant_type' : 'password'
} => inspect:type()
```
The failure occurs in the GUI, or on command line with option `-V`.
This is caused by an `XQRecordType` that has a `MapType` rather than the required `RecordType` as its `type`. The type is modified when `refineType` is called.
The change in this PR adds a dummy implementation of `refineType` to `XQRecordType`, such that the implementation in the base class is no longer used for `XQRecordType`.

Prevent type of `RecordType` from being refined to `MapType`

---

basex-core/src/main/java/org/basex/build/html/HtmlOptions.java
basex-core/src/main/java/org/basex/build/html/HtmlParser.java

The current state of the spec has HTML option `fail-on-error`, and it does not have `html-version` anymore.

Add HTML option fail-on-error, remove html-version

---

basex-core/src/main/java/org/basex/query/QueryError.java
basex-core/src/main/java/org/basex/query/QueryParser.java

This change implements the [recently modified](https://github.com/qt4cg/qtspecs/commit/e26b54c337ea4b1eea7d194a4555ca5218729589) `KeySpecifier` syntax.

Add support for extended `KeySpecifier` syntax

---

basex-tests/src/main/java/org/basex/tests/w3c/QT3TS.java

Some QT4 tests repeatedly fail because the implementation intentionally deviates from the specification. With this change, a list of these tests is now created so that their execution can be skipped.

Add blacklist for tests to be skipped due to conscious deviations from the spec
